twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    #form_themes: ['bootstrap_4_Horizontal_layout.html.twig']
    globals:
        app_environement: '%env(APP_ENV)%'
        appName: 'Nevrity'
        decRCCM: '11RA 23258'
        devise: 'Unité - Travail - Progrès'
        pays: 'France'
        appEmail: 'planning@nevrity-transports.com'
        siteweb: 'www.nevrity-transports.com'
        appPhone: '+33 (0)5 56 36 03 32'
        currency: ' €'
        ashtag: '#'
        appConcepteur: "BAYE Conception"

when@test:
    twig:
        strict_variables: true
