twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    #form_themes: ['bootstrap_4_Horizontal_layout.html.twig']
    globals:
        app_environement: '%env(APP_ENV)%'
        appName: 'Nevrity'
        decRCCM: '11RA 23258'
        devise: 'Unité - Travail - Progrès'
        pays: 'France'
        appEmail: 'contact@intellia.club'
        appPhone: '04 65 27 06 06'
        currency: ' €'
        ashtag: '#'
        appConcepteur: "BAYE Conception"

when@test:
    twig:
        strict_variables: true
