vich_uploader:
    db_driver: orm

    mappings:
        users_avatars:
            uri_prefix: /uploads/images/users
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\Base64Namer
            delete_on_update: true
            delete_on_remove: true

        conducteurs_images:
            uri_prefix: /uploads/images/conducteurs
            upload_destination: '%kernel.project_dir%/public/uploads/images/conducteurs'
            namer: Vich\UploaderBundle\Naming\Base64Namer
            delete_on_update: true
            delete_on_remove: true

        vehicules_images:
            uri_prefix: /uploads/images/vehicules
            upload_destination: '%kernel.project_dir%/public/uploads/images/vehicules'
            namer: Vich\UploaderBundle\Naming\Base64Namer
            delete_on_update: true
            delete_on_remove: true
